# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pUqXA2y6epwdMV7lcqrf2rmJWCUDIwK4
"""

import streamlit as st
import numpy as np
import tensorflow as tf
import pickle
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Load tokenizer and model
with open("tokenizer.pkl", "rb") as f:
    tokenizer = pickle.load(f)

model = tf.keras.models.load_model("sentiment_model.h5")

# Constants
MAX_SEQUENCE_LENGTH = 200

# Web App UI
st.set_page_config(page_title="IMDb Sentiment Analyzer")
st.title("🎬 IMDb Review Sentiment Analyzer")
st.markdown("Enter a movie review below and let the model predict whether it's positive or negative.")

# Input Text
user_input = st.text_area("Enter your review here:", "This movie was fantastic! The acting was brilliant.")

# Prediction Button
if st.button("Analyze Sentiment"):
    if user_input.strip():
        # Preprocess and predict
        sequence = tokenizer.texts_to_sequences([user_input])
        padded = pad_sequences(sequence, maxlen=MAX_SEQUENCE_LENGTH)
        prediction = model.predict(padded)[0][0]

        sentiment = "😊 Positive" if prediction > 0.5 else "😞 Negative"
        st.subheader("Prediction")
        st.write(f"**Sentiment:** {sentiment}")
        st.progress(prediction if prediction > 0.5 else 1 - prediction)
    else:
        st.warning("Please enter a review before analyzing.")