# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pUqXA2y6epwdMV7lcqrf2rmJWCUDIwK4
"""

import streamlit as st
import numpy as np
import tensorflow as tf
import pickle
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Load tokenizer and model
with open("tokenizer.pkl", "rb") as f:
    tokenizer = pickle.load(f)

model = tf.keras.models.load_model("sentiment_model.h5")

# Streamlit UI
st.set_page_config(page_title="IMDb Sentiment Analyzer", layout="centered")
st.title("🎬 IMDb Movie Review Sentiment Analyzer")

user_input = st.text_area("Enter a movie review:", height=150)

if st.button("Analyze Sentiment"):
    if user_input.strip() == "":
        st.warning("Please enter a review before clicking Analyze.")
    else:
        # Preprocess input
        sequences = tokenizer.texts_to_sequences([user_input])
        padded_input = pad_sequences(sequences, maxlen=200)

        # Make prediction
        prediction = model.predict(padded_input)[0][0]

        # Adjust and clamp progress value
        progress_value = prediction if prediction > 0.5 else 1 - prediction
        progress_value = max(0.0, min(1.0, progress_value))  # Ensure it's between 0.0 and 1.0

        # Display sentiment and progress
        if prediction > 0.5:
            st.success("✅ Positive Review")
        else:
            st.error("❌ Negative Review")

        st.progress(progress_value)
        st.write(f"Model confidence: **{progress_value * 100:.2f}%**")